import React from 'react';

export default function SampleOutput() {
  return (
    <section id="sample-output" className="py-20" style={{ background: 'var(--bg-secondary)' }}>
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-10">
          <h2 className="text-3xl sm:text-4xl font-bold" style={{ color: 'var(--text-primary)' }}>
            What your report looks like
          </h2>
          <p className="max-w-2xl mx-auto mt-4 text-base sm:text-lg" style={{ color: 'var(--text-secondary)', opacity: 0.9 }}>
            One screen of structured feedback so you know exactly what to practice next.
          </p>
        </div>

        {/* Screenshot mockup */}
        <div className="mx-auto rounded-3xl p-1 bg-gradient-to-r from-indigo-500 via-cyan-500 to-purple-500" style={{ maxWidth: 920 }}>
          <div className="bg-[#0f172a] rounded-3xl p-10" style={{ border: '1px solid rgba(255,255,255,0.1)' }}>
            <div className="flex flex-col lg:flex-row gap-10">
              {/* Left pane */}
              <div className="flex-1">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <div className="text-sm font-semibold" style={{ color: 'var(--accent)' }}>
                      Interview Score
                    </div>
                    <div className="text-5xl font-extrabold" style={{ color: 'white' }}>
                      82
                    </div>
                    <div className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                      /100 overall
                    </div>
                  </div>
                  <div className="flex flex-col items-end">
                    <span className="text-xs uppercase tracking-widest" style={{ color: 'var(--text-secondary)' }}>
                      Date
                    </span>
                    <span className="text-sm font-semibold" style={{ color: 'white' }}>
                      Mar 15, 2026
                    </span>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  {[
                    { label: 'Communication', value: 78 },
                    { label: 'Structure', value: 84 },
                    { label: 'Depth', value: 72 },
                    { label: 'Confidence', value: 80 }
                  ].map((item) => (
                    <div key={item.label} className="rounded-2xl p-4" style={{ background: 'rgba(255,255,255,0.05)' }}>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-semibold" style={{ color: 'white' }}>
                          {item.label}
                        </span>
                        <span className="text-sm font-bold" style={{ color: 'var(--accent)' }}>
                          {item.value}%
                        </span>
                      </div>
                      <div className="w-full h-2 rounded-full bg-white/10">
                        <div className="h-full rounded-full" style={{ width: `${item.value}%`, background: 'linear-gradient(90deg, #34d399, #22c55e)' }} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Right pane */}
              <div className="flex-1">
                <div className="rounded-2xl p-6" style={{ background: 'rgba(255,255,255,0.04)' }}>
                  <div className="text-sm font-semibold mb-4" style={{ color: 'var(--accent)' }}>
                    Top recommendation
                  </div>
                  <p className="text-sm" style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                    You transitioned well between topics, but you can boost impact by quantifying outcomes (e.g., “reduced load time by 37%” vs “faster”).
                  </p>
                </div>

                <div className="mt-6 rounded-2xl p-6" style={{ background: 'rgba(255,255,255,0.04)' }}>
                  <div className="text-sm font-semibold mb-4" style={{ color: 'var(--accent)' }}>
                    Next action
                  </div>
                  <ul className="list-disc list-inside text-sm" style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                    <li>Record 2 answers focusing on metrics</li>
                    <li>Practice using the STAR framework</li>
                    <li>Retry the same prompt in 3 days and compare</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <p className="mt-6 text-center text-xs" style={{ color: 'var(--text-secondary)', opacity: 0.7 }}>
          Screenshot is an illustrative example of a real report generated by Lana AI.
        </p>
      </div>
    </section>
  );
}
